# -*- coding: utf-8 -*-
"""EC_F_PES2UG23CS336.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EB1P-8YAdYaZJy8kfw5qeI7aUWBxW24R
"""

code = r'''
import torch

def _entropy_from_counts(counts: torch.Tensor) -> float:
    total = counts.sum()
    if total.item() == 0:
        return 0.0
    probs = counts.float() / total.float()
    mask = probs > 0
    ent = -(probs[mask] * torch.log2(probs[mask])).sum()
    return float(ent.item())

def get_entropy_of_dataset(tensor: torch.Tensor):
    y = tensor[:, -1]
    _, counts = torch.unique(y, return_counts=True)
    return _entropy_from_counts(counts)

def get_avg_info_of_attribute(tensor: torch.Tensor, attribute: int):
    N = tensor.shape[0]
    if N == 0:
        return 0.0
    y = tensor[:, -1]
    Xa = tensor[:, attribute]
    values, vcounts = torch.unique(Xa, return_counts=True)

    avg_info = 0.0
    for v, cnt in zip(values, vcounts):
        mask = (Xa == v)
        y_sub = y[mask]
        _, sub_counts = torch.unique(y_sub, return_counts=True)
        weight = float(cnt.item()) / float(N)
        avg_info += weight * _entropy_from_counts(sub_counts)
    return float(avg_info)

def get_information_gain(tensor: torch.Tensor, attribute: int):
    h = get_entropy_of_dataset(tensor)
    avg = get_avg_info_of_attribute(tensor, attribute)
    ig = h - avg
    if abs(ig) < 1e-12:
        ig = 0.0
    return round(float(ig), 4)

def get_selected_attribute(tensor: torch.Tensor):
    n_attrs = tensor.shape[1] - 1  # last column is target
    gains = {a: get_information_gain(tensor, a) for a in range(n_attrs)}
    best_attr = max(gains.items(), key=lambda kv: (kv[1], -kv[0]))[0]
    return gains, best_attr
'''
with open("EC_F_PES2UG23CS336_Lab3.py", "w") as f:
    f.write(code)
print("File saved: EC_F_PES2UG23CS336_Lab3.py")

!python test.py --ID EC_F_PES2UG23CS336_Lab3 --data mushrooms.csv --framework pytorch

!python test.py --ID EC_F_PES2UG23CS336_Lab3 --data tictactoe.csv --framework pytorch

!python test.py --ID EC_F_PES2UG23CS336_Lab3 --data Nursery.csv --framework pytorch

!python test.py --ID EC_F_PES2UG23CS336_Lab3 --data mushrooms.csv --framework pytorch --print-tree

!python test.py --ID EC_F_PES2UG23CS336_Lab3 --data tictactoe.csv --framework pytorch --print-tree

!python test.py --ID EC_F_PES2UG23CS336_Lab3 --data Nursery.csv --framework pytorch --print-tree